const EnglishDictionary={
	Home: "Home",
	AboutUs: "About Us",
	Services: "Services",
	Service1: "Service 1",
	Service2: "Service 2",
	Service3: "Service 3",
	Products: "Products",
	Careers: "Careers",
	News: "News",
	Doc: "Documentation",
	Doc1: "Documentation 1",
	Doc2: "Documentation 2",
	Doc3: "Documentation 3",
	Doc4: "Documentation 4",
	Doc5: "Documentation 5",
	Login: "Login",
	Register: "Register",
	Text01: "The best numbers for your work,<br> rest and just inspiration",
	Text02: "Seat reservation in the best hotel 2019 by version «Hotel's review» association",
	Text03: "Receive our latest news and promotions in your inbox!",
	Text04: "We'll find a numbers for your desires",
	Text05: "You have still Toxin's account",
	Text06: "Have you not Toxin's account?",
	Text07: "May invite the guests <br> (up to 10 peoples)",
	Text08: "The wide number passage isn't less then 91 cm.",
	Text09: "The technician recieve you on ground floor and see you to the number.",
	Copyright: "Copyright © 2018 Toxin Hotel. All rights reserved.",
	Navigation: "Navigation",
	Support: "Support",
	WhoWeAre: "Who We Are",
	OurTeam: "Our Team",
	Investors: "Investors",
	Community: "Community",
	GetInTouch: "Get In Touch",
	Arrival: "Arrival",
	Departure: "Departure",
	Guests: "Guests",
	Clean: "Clean",
	Apply: "Apply",
	Adults: "Adults",
	Children: "Children",
	BabiesInArms: "Babies in Arms",
	Subscription: "Subscribe to Our Newsletter",
	AccountRegistration: "Account Registration",
	Male: "Male",
	Female: "Female",
	DateOfBirth: "Date Of Birth",
	GetSpecialOffers: "Get Special Offers",
	TheNumberWhat: "The numbers, what we have found you",
	RangePrice: "Range Price",
	ThePriceForBeing: "The price for being in the number by day",
	Reviews: "Reviews",
	ByDay: "by day",
	Hotel_sBeingDates: "Hotel's being dates",
	Improvements: "Improvements",
	MayBeWithPets: "May be with pets",
	MaySmoke: "May smoke",
	Accessibility: "Accessibility",
	HelperService: "The helper for the disabled person",
	BroadPassage: "Broad Passage",
	NumberImprovements:"Number Improvements",
	Bedrooms: "Bedrooms",
	Beds: "Beds",
	Bathrooms: "Bathrooms",
	AuxiliaryImprovements: "Auxiliary Improvements",
	Breakfast: "Breakfast",
	WritingTable: "Writing Table",
	BreastfeedingChair: "Breastfeeding Chair",
	Cot: "Cot",
	Television: "Television",
	Shampoo:"Shampoo",
	Account:"Account",
}
const GBBEnglishDictionary={
	Login: ["Login", "79px"],
	Register: ["Register", "101px"],
	Register2: ["Register", "101px"],
	SelectNumber: ["Select Number", "100%"],
	GoToPayment: ["Go to payment", "100%"],
}
const PlaceholderEnglishDictionary={
	dmy:["dd.mm.yyyy"],
	dmy2:["dd.mm.yyyy - dd.mm.yyyy"],
	HowManyGuests:["How many guests", "guest", "guests", "baby in arms", "babies in arms",],
	EMail:["Email"],
	NumberImprovements:["Number Improvements", "badroom", "badrooms", "bed", "beds", "bathroom", "bathrooms",],
	FirstName:["First Name"],
	LastName:["Last Name"],
	Password:["Password"],
}
const PseudoelementEnglishDictionary={
	Lux:["numb-prev__desc-numb_lux-en","numb-prev__desc-numb_lux-ru",],
}
