const EnglishDictionary={
	Home: "Home",
	AboutUs: "About Us",
	Services: "Services",
	Products: "Products",
	Careers: "Careers",
	News: "News",
	Doc: "Documentation",
	Login: "Login",
	Register: "Register",
	Text01: "The best numbers for your work,<br> rest and just inspiration",
	Text02: "Seat reservation in the best hotel 2019 by version «Hotel's review» association",
	Text03: "Receive our latest news and promotions in your inbox!",
	Text04: "We'll find a numbers for your desires",
	Copyright: "Copyright © 2018 Toxin Hotel. All rights reserved.",
	Navigation: "Navigation",
	Support: "Support",
	WhoWeAre: "Who We Are",
	OurTeam: "Our Team",
	Investors: "Investors",
	Community: "Community",
	GetInTouch: "Get In Touch",
	Arrival: "Arrival",
	Departure: "Departure",
	Guests: "Guests",
	Clean: "Clean",
	Apply: "Apply",
	Adults: "Adults",
	Children: "Children",
	BabiesInArms: "Babies in Arms",
	//SelectNumber: "Select Number",
	Subscription: "Subscribe to Our Newsletter",
}
const GBBEnglishDictionary={
	Login: ["Login", "79px"],
	Register: ["Register", "101px"],
	SelectNumber: ["Select Number", "100%"],
}
const PlaceholderEnglishDictionary={
	dmy:{Default: "dd.mm.yyyy"},
	HowManyGests:{Default: "How many gests"},
	EMail:{Default: "Email"},
}
