const RussianDictionary={
	Home: "На главную",
	AboutUs: "О Нас",
	Services: "Услуги",
	Service1: "Услуга 1",
	Service2: "Услуга 2",
	Service3: "Услуга 3",
	Products: "Услуги",
	Careers: "Вакансии",
	News: "Новости",
	Doc: "Соглашения",
	Doc1: "Соглашение 1",
	Doc2: "Соглашение 2",
	Doc3: "Соглашение 3",
	Doc4: "Соглашение 4",
	Doc5: "Соглашение 5",
	Login: "Войти",
	Register: "Зарегистрироваться",
	Text01: "Лучшие номера для вашей работы,<br> отдыха и просто вдохновения",
	Text02: "Бронирование номеров в лучшем отеле 2019 года по версии ассоциации «Отельные взгляды»",
	Text03: "Получайте специальные предложения и новости сервиса",
	Text04: "Найдём номера под ваши пожелания",
	Text05: "Уже есть аккаунт на Toxin",
	Text06: "Нет аккаунта на Toxin?",
	Text07: "Можно пригласить гостей <br> (до 10 человек)",
	Text08: "Ширина коридоров в номере не менее 91 см.",
	Text09: "На 1 этаже вас встретит специалист и проводит до номера.",
	Copyright: "Авторские права © 2018 Токсин отель. Все права защищены.",
	Navigation: "Навигация",
	Support: "Служба поддержки",
	WhoWeAre: "О сервисе",
	OurTeam: "Наша команда",
	Investors: "Инвесторы",
	Community: "Сообщества",
	GetInTouch: "Связь с нами",
	Arrival: "Прибытие",
	Departure: "Выезд",
	Guests: "Гости",
	Clean: "Очистить",
	Apply: "Применить",
	Adults: "Взрослые",
	Children: "Дети",
	BabiesInArms: "Младенцы",
	Subscription: "Подписка",
	AccountRegistration: "Регистрация аккаунта",
	Male: "Мужчина",
	Female: "Женщина",
	DateOfBirth: "Дата рождения",
	GetSpecialOffers: "Получать спецпредложения",
	TheNumberWhat: "Номера, которые мы для вас подобрали",
	RangePrice: "Диапазон цены",
	ThePriceForBeing: "Стоимость за сутки пребывания в номере",
	Reviews: "Отзывов",
	ByDay: "в сутки",
	Hotel_sBeingDates: "Даты пребывания в отеле",
	Improvements: "Удобства",
	MayBeWithPets: "Можно с питомцами",
	MaySmoke: "Можно курить",
	Accessibility: "Доступность",
	HelperService: "Помощник для инвалидов",
	BroadPassage: "Широкий коридор",
	NumberImprovements:"Удобства номера",
	Bedrooms: "Спальни",
	Beds: "Кровати",
	Bathrooms: "Ванные комнаты",
	AuxiliaryImprovements: "Дополнительные удобства",
	Breakfast: "Завтрак",
	WritingTable: "Письменный стол",
	BreastfeedingChair: "Стул для кормления",
	Cot: "Кроватка",
	Television: "Телевизор",
	Shampoo:"Шампунь",
	Account:"Данные для входа в сервис",
}
const GBBRussianDictionary={
	Login: ["Войти", "87px"],
	Register: ["Зарегистрироваться", "196px"],
	Register2: ["Создать", 	"99px"],
	SelectNumber: ["Подобрать номер", "100%"],
	GoToPayment: ["Перейти к оплате", "100%"],
}
const PlaceholderRussianDictionary={
	dmy:["дд.мм.гггг"],
	dmy2:["дд.мм.гггг - дд.мм.гггг"],
	HowManyGuests:["Сколько гостей", "гость", "гостя", "гостей", "младенец", "младенца", "младенцев",],
	EMail:["Электронный адрес"],
	NumberImprovements:["Удобства номера", "спальня", "спальни", "спален", "кровать", "кровати", "кроватей", "ванная комната", "ванные комнаты", "ванных комнат",],
	FirstName:["Имя"],
	LastName:["Фамилия"],
	Password:["пароль"],
}
const PseudoelementRussianDictionary={
	Lux:["numb-prev__desc-numb_lux-ru","numb-prev__desc-numb_lux-en",],
}

const JSPhraseRussianDictionary={
	DoughnutQuality: ['Разочарован','Удовлетворительно','Хорошо','Великолепно'],
}
