const RussianDictionary={
	Home: "На главную",
	AboutUs: "О Нас",
	Services: "Услуги",
	Products: "Услуги",
	Careers: "Вакансии",
	News: "Новости",
	Doc: "Соглашения",
	Login: "Войти",
	Register: "Зарегистрироваться",
	Text01: "Лучшие номера для вашей работы,<br> отдыха и просто вдохновения",
	Text02: "Бронирование номеров в лучшем отеле 2019 года по версии ассоциации «Отельные взгляды»",
	Text03: "Получайте специальные предложения и новости сервиса",
	Text04: "Найдем номера под ваши пожелания",
	Copyright: "Авторские права © 2018 Токсин отель. Все права защищены.",
	Navigation: "Навигация",
	Support: "Служба поддержки",
	WhoWeAre: "О сервисе",
	OurTeam: "Наша команда",
	Investors: "Инвесторы",
	Community: "Сообщества",
	GetInTouch: "Связь с нами",
	Arrival: "Прибытие",
	Departure: "Выезд",
	Guests: "Гости",
	Clean: "Очистить",
	Apply: "Применить",
	Adults: "Взрослые",
	Children: "Дети",
	BabiesInArms: "Младенцы",
	//SelectNumber: "Подобрать номер",
	Subscription: "Подписка",
}
const GBBRussianDictionary={
	Login: ["Войти", "87px"],
	Register: ["Зарегистрироваться", "196px"],
	SelectNumber: ["Подобрать номер", "100%"],
}
const PlaceholderRussianDictionary={
	dmy:{Default: "дд.мм.гггг"},
	HowManyGests:{Default: "Сколько гостей"},
	EMail:{Default: "Электронный адрес"},
}
