const EnglishDictionary={
	Home: "Home",
	AboutUs: "About Us",
	Services: "Services",
	Products: "Products",
	Careers: "Careers",
	News: "News",
	Doc: "Documentation",
	Login: "Login",
	Register: "Register",
	Text01: "The best numbers for your work,<br> rest and just inspiration",
	Text02: "Seat reservation in the best hotel 2019 by version «Hotel's review» association",
	Text03: "Receive our latest news and promotions in your inbox!",
	Text04: "We'll find a numbers for your desires",
	Text05: "You have still Toxin's account",
	Text06: "Have you not Toxin's account?",
	Copyright: "Copyright © 2018 Toxin Hotel. All rights reserved.",
	Navigation: "Navigation",
	Support: "Support",
	WhoWeAre: "Who We Are",
	OurTeam: "Our Team",
	Investors: "Investors",
	Community: "Community",
	GetInTouch: "Get In Touch",
	Arrival: "Arrival",
	Departure: "Departure",
	Guests: "Guests",
	Clean: "Clean",
	Apply: "Apply",
	Adults: "Adults",
	Children: "Children",
	BabiesInArms: "Babies in Arms",
	Subscription: "Subscribe to Our Newsletter",
	AccountRegistration: "Account Registration",
	Male: "Male",
	Female: "Female",
	DateOfBirth: "DateOfBirth",
	GetSpecialOffers: "Get Special Offers",
	TheNumberWhat: "The numbers, what we have found you",
}
const GBBEnglishDictionary={
	Login: ["Login", "79px"],
	Register: ["Register", "101px"],
	SelectNumber: ["Select Number", "100%"],
	GoToPayment: ["Go to payment", "100%"],
}
const PlaceholderEnglishDictionary={
	dmy:["dd.mm.yyyy"],
	HowManyGuests:["How many guests", "guest", "guests", "baby in arms", "babies in arms",],
	EMail:["Email"],
}
